name: Compilar APK Iglesia
on:
  push:
    branches: [ principal, main ]

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK Exacto
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Forzamos la versión estable esperada por Flet

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install flet[cli]
          pip install -r requirements.txt

      - name: Compilar Aplicación Android (.apk) Autoconfirmada
        run: |
          export FLUTTER_NO_INTERACTIVE=true
          export PUB_HOSTED_URL=https://dartlang.org
          
          # TRUCO MAESTRO: 'echo "y"' responde automáticamente "Sí" a cualquier pregunta de la consola
          echo "y" | flet build apk
          
      - name: Guardar Instalador Listo
        uses: actions/upload-artifact@v4
        with:
          name: App_Iglesia_Celular
          path: build/apk/*.apk
