name: Compilar APK Iglesia
on:
  push:
    branches: [ principal ] # Detecta tu rama llamada 'principal'

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java y Entorno Android
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias de Python y Flet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compilar Aplicación Android (.apk)
        run: |
          # El punto '.' le indica a Flet que compile todo el directorio actual
          flet build apk . --no-version-check

      - name: Guardar Instalador Listo
        uses: actions/upload-artifact@v4
        with:
          name: App_Iglesia_Celular
          path: build/apk/*.apk
